### ISSUE TITLE
Pick up the Evernote token

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.client#13]
Either read it from `../vaani.setup/oauthToken.json` or let [vaani.setup](https://github.com/mozilla/vaani.setup) put it into your `config.json`. 
After a token update the client also needs to be signaled or restarted.

**Comment by andrenatal** [comment]
I guess this is something that @davidflanagan was already taking care, not?

**Comment by davidflanagan** [comment]
Yes PR#11 reads the token from an environment variable. I'm now working on a patch to vaani.setup that will set the environment variable.  I'll be testing and landing it today.
