### ISSUE TITLE
Dependency building time

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.client#14]
At the moment the client requires too many bleeding edge dependencies. This leads to very long native build times on smaller machines. Especially the Pocketsphinx->CMake dependency graph.

**Comment by andrenatal** [comment]
The team is working to have prebuilt images of Rpi and Yocto with all dependencies required.

We discussed this morning that the dependency building time has nothing to do with the code on this repo, but with the architecture chosen to run it. So I'd rather have on this repo just issues related with the code that lies here.
