### ISSUE TITLE
The keyword spotter leaves some keyword end-sound ("th") on the stream

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.client#15]
This end sound is from time to time resulting in STT results like "the add xy to the shopping list" or even "this add xy to the shopping list".

**Comment by andrenatal** [comment]
@tilmankamp are you running the latest code? I did some fixing regarding this issue yesterday night.

**Comment by andrenatal** [comment]
@tilmankamp How can I access the files that was streamed to the server?

**Comment by andrenatal** [comment]
Fixed #18
