### ISSUE TITLE
crash at index.js:126 if logs/ directory does not exist

### ISSUE THREAD

**Issue by davidflanagan** [mozilla/vaani.client#16]
This line causes a fatal exception if there is not a logs/ directory:

```
      logStream  = fs.createWriteStream("logs/" +  new Date().getTime(), {'\
```

flags': 'a'});

Could be fixed by just adding something to the README saying to create logs/
Or by adding a fs.mkdirSync (or whatever the call is)

**Comment by andrenatal** [comment]
Fixed at #18
