### ISSUE TITLE
Please add a LICENSE file to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/vaani.client#3]
MPL2 is generally preferred by Mozilla for code repositories, but if you must use a different license for whatever reason, that's fine.

**Comment by kdavis-mozilla** [comment]
The license was/is specified in [package.json](https://github.com/mozilla/vaani.client/blob/master/package.json), but I've also added its full text in commit [4fea02e](https://github.com/mozilla/vaani.client/commit/4fea02e54858423aa4651d4fc9ab95069d491fd5)
