### ISSUE TITLE
We need to change the wakeword

### ISSUE THREAD

**Issue by davidflanagan** [mozilla/vaani.client#56]
In US English, "foxy" means "sexy", which does not seem an appropriate name for our device.

Also, I think we've been told that we can't make any references to firefox in our brands. That's why the "foxlink" project had to change to "project link".  So I think that marketing and legal won't let us use "foxy" either.

@andrenatal have you experimented with other wakewords or phrases? Does "Hey Vaani" or "Ok Vaani" (or both) work well enough?  (Do we have to add the word "Vaani" to the Pocketsphinx dictionary to make it work?)

**Comment by davidflanagan** [comment]
I sent the recordings we got from murmur to the team by email. I hope they help. I'll be on PTO all next week so not really able to do anything else on this issue.

**Comment by andrenatal** [comment]
These phrases aren't performing well neither with the adaptation using the sentences captured by Murmur. So more research is still required.

**Comment by davidflanagan** [comment]
Do you think that "List maker" would work? That was one of the ones on Tif's list, and I obtained murmur samples for it. If we ever hope to add other skills to the Vaani device, and wanted to use different wakewords for different skills, then having a wakeword that does not include "vaani" would be good, I suppose.

**Comment by andrenatal** [comment]
@davidflanagan  Yes, with this keyword performed much better. I'm pushing a PR. Please, test it and let me know if that works for you.
