### ISSUE TITLE
Don't say hello when restarted by Chris' service

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/vaani.client#57]
As the restart may occur at say 3am the client shouldn't say hi then, but should on first time setup.

**Comment by andrenatal** [comment]
We need to change the service to pass a parameter to the client ignore the hello beep right in the beginning.

**Comment by andrenatal** [comment]
Following PRs are also part of this fix:

[git-auto-updater](https://github.com/mozilla/git-auto-updater/commit/74cd919562ec0fe0afea54edbd67d2437ff54ff7)

[vaani.config](https://github.com/moz-vaani/vaani.config/pull/1)
