### ISSUE TITLE
Sometimes the app hangs and return after a little

### ISSUE THREAD

**Issue by andrenatal** [mozilla/vaani.client#62]
We don't know if is the mic (at the OS alsa sharing level or at node level), or the node app itself, but sometimes the mic stops listening and the app hangs for a while then comeback later.

**Comment by davidflanagan** [comment]
can you tell from the journalctl whether it is exiting and being restarted by systemd, or is it continuing to run and being unresponsive?

**Comment by andrenatal** [comment]
Continues to run being unresponsive and then suddenly it returns.

**Comment by andrenatal** [comment]
The journalctl just stays stucked, without any cnm calculation [1] that happens when the audio is being fed to the pocketsphinx engine.

Jul 28 14:00:07 Vaani-andre node[347]: INFO: cmn_prior.c(99): cmn_prior_update: from < 22.36 -2.94 -9.37 -0.58  4.86 -7.71  4.49  6.63 -4.91 -0.72  4.99 -1.19  1.83 >

**Comment by davidflanagan** [comment]
I wonder if something is going wrong in the mic library or in wakeword... Maybe add logging to wakeword to see if it is even getting data from the microphone?

**Comment by andrenatal** [comment]
That's my wonder too, but at least now it's not deadlocking anymore, just this hangs, and pretty intermittent. Let's do more debugging...

**Comment by kdavis-mozilla** [comment]
Just a thought, haven't tried to verify this yet, but maybe Chris's [git-auto-updater](https://github.com/mozilla/git-auto-updater) wakes up at these inopportune times and in doing so causes this problem somehow. (I'll try to collect more data to see if this is the case.)

**Comment by kdavis-mozilla** [comment]
Tried to "talk over" the git-auto-updater check once and it seemed to work. I'll try again and see my luck.

**Comment by kdavis-mozilla** [comment]
Tried again to "talk over an update" and it still worked with no problem and no hang.

**Comment by kdavis-mozilla** [comment]
Did it! Talked over the update and I got the hang. I'll try a few more times.

**Comment by kdavis-mozilla** [comment]
Tried a few more times and can't get any consistent correlation between the update and the hang. The coincided once, out of maybe 8 tries. If the two are related, the relation is hard to tease out.

**Comment by davidflanagan** [comment]
vaani.client uses the wakeword repo, and that repo uses the npm 'mic' package. I think that adding logging to one or both of those packages might help here.  I think it would be interesting to know whether we are even getting data from the microphone during these hangs. If so, then the problem is probably in PocketSphinx. But if not, then we need to look lower.

**Comment by andrenatal** [comment]
@davidflanagan We have a suspicion that the server may be blocking/delaying the response to the client that gives us the impression of blocking. We added more logs to try to monitor and @kdavis-mozilla and @tilmankamp are investigating it.

**Comment by kdavis-mozilla** [comment]
Possibly solved by commits [d4224b4](https://github.com/mozilla/vaani.server/commit/d4224b400664091adf8ce4822a9c2c487912aba9) and [68bbc49](https://github.com/mozilla/vaani.server/commit/68bbc4989ccd6d88cd37bad5da901ba42d815a02) to vaani.server, but more testing is required.

**Comment by kdavis-mozilla** [comment]
After testing the commits above on vaani.server, it seems as if this is fixed.
